"""
minio_bootstrap.py — idempotent MinIO setup for OSP integration testing.

Run once after `task integration:minio:up`.  It:

1. Waits for the MinIO S3 API to be ready.
2. Creates (or reuses) the test bucket.
3. Writes a `.env.minio` file so server.py and the tests can pick up
   the generated credentials.

All steps are idempotent — safe to run multiple times.
"""

from __future__ import annotations

import time
from pathlib import Path

import boto3
import botocore.config
import botocore.exceptions

# ── Configuration ─────────────────────────────────────────────────────────────

MINIO_HOST = "localhost"
MINIO_PORT = 9000
MINIO_ROOT_USER = "minioadmin"
MINIO_ROOT_PASSWORD = "minioadmin"
MINIO_REGION = "us-east-1"
MINIO_BUCKET = "test-bucket-minio"

# OSP frontend credentials clients will use when talking to the MinIO bucket
OSP_CLIENT_ACCESS_KEY = "osp-client"
OSP_CLIENT_SECRET_KEY = "osp-client-secret"

OSP_PROXY_HOST = "localhost"
OSP_PROXY_PORT = 6190
OSP_METRICS_PORT = 9091

HERE = Path(__file__).parent


# ── Helpers ───────────────────────────────────────────────name─────────────────


def _s3_client() -> "boto3.client":
    return boto3.client(
        "s3",
        endpoint_url=f"http://{MINIO_HOST}:{MINIO_PORT}",
        aws_access_key_id=MINIO_ROOT_USER,
        aws_secret_access_key=MINIO_ROOT_PASSWORD,
        region_name=MINIO_REGION,
        config=botocore.config.Config(
            signature_version="s3v4",
            s3={"addressing_style": "path"},
            retries={"max_attempts": 1},
        ),
    )


def wait_for_minio(timeout: int = 30) -> None:
    print("⏳ Waiting for MinIO S3 API …")
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            s3 = _s3_client()
            s3.list_buckets()
            print("✅ MinIO is ready.")
            return
        except Exception:
            pass
        time.sleep(1)
    raise RuntimeError("MinIO did not become ready in time.")


def create_bucket(s3) -> None:
    try:
        s3.head_bucket(Bucket=MINIO_BUCKET)
        print(f"   Bucket '{MINIO_BUCKET}' already exists.")
    except botocore.exceptions.ClientError as e:
        if e.response["Error"]["Code"] in ("404", "NoSuchBucket"):
            s3.create_bucket(Bucket=MINIO_BUCKET)
            print(f"   Created bucket '{MINIO_BUCKET}'.")
        else:
            raise


def write_env(env_path: Path) -> None:
    content = f"""\
# Auto-generated by minio_bootstrap.py — do not edit manually.

# ── MinIO backend ─────────────────────────────────────────────────────────────
MINIO_HOST={MINIO_HOST}
MINIO_PORT={MINIO_PORT}
MINIO_REGION={MINIO_REGION}
MINIO_BUCKET={MINIO_BUCKET}
MINIO_ACCESS_KEY_ID={MINIO_ROOT_USER}
MINIO_SECRET_ACCESS_KEY={MINIO_ROOT_PASSWORD}

# ── OSP proxy (frontend client credentials) ───────────────────────────────────
OSP_PROXY_HOST={OSP_PROXY_HOST}
OSP_PROXY_PORT={OSP_PROXY_PORT}
OSP_METRICS_PORT={OSP_METRICS_PORT}
OSP_CLIENT_ACCESS_KEY={OSP_CLIENT_ACCESS_KEY}
OSP_CLIENT_SECRET_KEY={OSP_CLIENT_SECRET_KEY}
"""
    env_path.write_text(content)
    print(f"   Wrote {env_path}")


# ── Main ──────────────────────────────────────────────────────────────────────


def main() -> None:
    wait_for_minio()
    s3 = _s3_client()

    print("🪣 Setting up bucket …")
    create_bucket(s3)

    print("📝 Writing .env.minio …")
    write_env(HERE / ".env.minio")

    print("✅ MinIO bootstrap complete.")


if __name__ == "__main__":
    main()
