[package]
name = "object-storage-proxy"
version = "0.5.1"
edition = "2024"
description = "A fast in-process reverse proxy for AWS S3 and IBM COS with a Python interface for auth and credential management."
license = "MIT"
homepage = "https://osp.flexworks.eu"
repository = "https://github.com/opensourceworks-org/object-storage-proxy"
readme = "README.md"
keywords = ["s3", "proxy", "object-storage", "ibm-cos", "pingora"]
categories = ["network-programming", "web-programming::http-server"]

[dependencies]
async-trait = "0.1.89"
prometheus = "0.14.0"
clap = { version = "4.6.1", features = ["derive"] }
log = "0.4.29"
env_logger = "0.11.10"
# pingora = { version = "0.4.0", features = ["proxy", "openssl"] }
pingora = { version = "0.8.0", features = ["proxy", "rustls"] }
futures = "0.3.32"
http = "1.4.0"
serde_json = "1.0.149"
reqwest = { version = "0.12.28", features = ["json", "rustls-tls"] }
tokio = { version = "1.52.3", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
dotenv = "0.15.0"
nom = "8.0.0"
wiremock = "0.6.5"

# openssl = { version = "0.10.72", features = ["vendored"] }

pyo3 = { version = "0.25.1", features = [
  "extension-module",
  "serde",
  "macros",
] }
chrono = "0.4.44"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = [
  "fmt",
  "env-filter",
  "chrono",
] }
rustls = { version = "0.23.40", features = [
  "ring",
  "logging",
  "tls12",
], default-features = false }
url = "2.5.8"
sha256 = "1.6.0"
ring = "0.17.14"
hex = "0.4.3"
regex = "1.12.3"
percent-encoding = "2.3.2"
bytes = "1.11.1"
async-stream = "0.3.6"
tokio-util = "0.7.18"
futures-core = "0.3.32"
pin-project-lite = "0.2.17"
base64 = "0.22.1"
urlencoding = "2.1.3"
dashmap = "6.1.0"
# sha2 = "0.10.9"
# hmac-sha256 = "1.1.8"

# [build-dependencies]
# openssl-sys = { version = "0.9", features = ["vendored"] }

[lib]
name = "object_storage_proxy"
crate-type = ["cdylib"]
path = "src/lib.rs"

[package.metadata.maturin]
bindings = "pyo3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1


[target.aarch64-unknown-linux-gnu.dependencies]
openssl = { version = "0.10.79", features = ["vendored"] }
